sklep_2/apps/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('added/<str:id>/', views.add_to_cart, name='add'),
    path('remove/<str:id>/', views.RemoveItem.as_view(), name='remove_item'),
    path('', views.MainCart.as_view(), name='main_cart'),
]

sklep_2/apps/order/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('', views.order, name='order'),
    path('parcels/', views.ParcelView.as_view(), name='parcel'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

sklep_2/apps/shop/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

app_name = 'shop'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('shop:password_change_done')), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('shop:password_reset_done')), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('shop:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('register/', views.Register.as_view(), name='register'),
    path('account/', views.account, name='account'),
    path('account/<str:type>/', views.account, name='account_data'),
    path('detail/<str:slug>/<int:seconds>/<int:hours>/<int:id>/', views.Detail.as_view(), name='detail'),
    path('list/category/<str:category>/', views.List.as_view(), name='list_category'),
    path('list/search/<str:search>/', views.List.as_view(), name='list_search'),
    path('list/', views.List.as_view(), name='list'),
    path('search/', views.search, name='search'),
    path('', views.Main.as_view(), name='main'),
]

sklep_2/sklep_2/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include


urlpatterns = i18n_patterns(
    # admin
    path('admin/', admin.site.urls),
    # apps
    path('', include('apps.shop.urls', namespace='shop')),
    path('analysis/', include('apps.analysis.urls', namespace='analysis')),
    path('cart/', include('apps.cart.urls', namespace='cart')),
    path('coupon/', include('apps.coupon.urls', namespace='coupon')),
    path('order/', include('apps.order.urls', namespace='order')),
    # authorization
    path('accounts/', include('allauth.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL) 

sklep_2/apps/order/models.py
from pyexpat import model
from django.core import validators
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db.models.base import Model
from django_countries.fields import CountryField
from phonenumber_field.modelfields import PhoneNumberField

from apps.shop.models import Product, UserModel, Address

class Order(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=200)
    phone_number = PhoneNumberField()
    street = models.CharField(max_length=100)
    street_number = models.CharField(max_length=10)
    ZIP_code = models.CharField(max_length=15)
    town = models.CharField(max_length=50)
    country = CountryField(max_length=60)
    discount = models.DecimalField(default=0, decimal_places=2, max_digits=3)
    paid = models.BooleanField(default=False)
    user = models.ForeignKey(UserModel, related_name='order', on_delete=models.SET_NULL, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f'{ self.last_name } { self.first_name }'
    
    def total_price(self):
        products = self.products.all()
        total = 0
        for product in products:
            total += product.total_price()
        return total



class OrderProduct(models.Model):
    order = models.ForeignKey(Order, related_name='products', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_product', on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField()

    def __str__(self) -> str:
        return f'{ str(self.id) } - { self.product.name }'
    
    def total_price(self):
        return self.quantity * self.product.price


class Parcel(Address):
    name = models.CharField(max_length=50)
    latitude = models.CharField(max_length=30)
    longitude = models.CharField(max_length=30)

    def __str__(self) -> str:
        return self.name



    

sklep_2/apps/shop/models.py
import os

from django.urls import reverse
from django_countries.fields import CountryField
from django.contrib.auth.models import AbstractUser
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField



def get_path_upload_to(self, filename):
    extension = filename.split('.')[-1]
    filename = f'{self.id}.{extension}'
    return os.path.join(f'products/', filename)


class Address(models.Model):
    street = models.CharField(max_length=100, null=True, blank=True)
    street_number = models.CharField(max_length=10, null=True, blank=True)
    ZIP_code = models.CharField(max_length=15, null=True, blank=True)
    town = models.CharField(max_length=50, null=True, blank=True)
    country = CountryField(max_length=60, null=True, blank=True)

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Address'
        verbose_name_plural = 'Addresses'


class UserModel(AbstractUser):
    address = models.ForeignKey(Address, models.SET_NULL, blank=True, null=True)
    number = PhoneNumberField(blank=True, null=True)
    class Meta:
        ordering = ('-last_name', '-first_name')
        verbose_name = 'UserModel'
        verbose_name_plural = 'UserModels'
    
    def __str__(self):
        return f'{self.last_name} {self.first_name} {self.id}'
    


class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField()

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
    
    
class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=250)
    slug = models.SlugField()
    image = models.ImageField(upload_to=get_path_upload_to, default='empty.png')
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    available = models.BooleanField(default=True)
    quantity_available = models.PositiveSmallIntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'Product'
        managed = True
        ordering = ['-id']
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
    
    def __str__(self):
        return f'{self.name}'
    
    def get_absolute_url(self):
        return reverse("shop:detail", args=[self.slug, 
                                       self.created.strftime('%S'), 
                                       self.created.strftime('%H'),
                                       self.id])
    
    def data(self):
        product =  {'name': self.name,
                    'url': self.get_absolute_url()
        } 
        return product
    
  
    

                                                                  

    





 
        

sklep_2/apps/shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _
from django_countries.widgets import CountrySelectWidget
from phonenumber_field.widgets import PhoneNumberPrefixWidget

from .models import Address, UserModel


class UserModelForm(UserCreationForm):

    class Meta:
        model = UserModel 
        fields = ('username', 'email', 'password1', 'password2')
        widgets = {'username': forms.TextInput(attrs={'class': 'register_input form-control shadow-none', 'placeholder': _('username'), 'required': 'required'}),
                   'email': forms.TextInput(attrs={'class': 'register_input form-control shadow-none form-check-input', 'placeholder': _('email'), 'type': 'email', 'required': 'required'}),
                #    'number': PhoneNumberPrefixWidget(initial='PL', attrs={'class': 'phone_number_register  shadow-none  phonenumber font_size_1', 'minlength': '9', 'required': 'required'})
                }
        labels = {
            'username': _('Username'),
            'email': _('Email'),
            # 'number': _('Phone Number')
        }
                     
    error_messages = {
        'password_mismatch': _('The two password fields didn`t match'),
    }

class PersonalForm(forms.ModelForm):
    class Meta:
        model = UserModel
        fields = ('first_name', 'last_name', 'email', 'number')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control font_numbers_light input', 'pattern': '^[A-ZŻŹŁ][a-zęóąśłżźćń]*', 'placeholder': '-----', 'required': 'required', 'disabled': 'disabled'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control font_numbers_light input', 'pattern': '^[A-ZŻŹŁ][a-zęóąśłżźćń]*', 'placeholder': '-----', 'required': 'required', 'disabled': 'disabled'}),
            'email': forms.TextInput(attrs={'class': 'form-control font_numbers_light input', 'type': 'email', 'placeholder': '-----', 'required': 'required', 'disabled': 'disabled'}),
            'number': PhoneNumberPrefixWidget(initial='PL', attrs={'class': 'input font_numbers_light phonenumber form-control', 'placeholder': '-----', 'pattern': '[0-9]{9,12}', 'required': 'required', 'disabled': 'disabled'}),
        }
        labels = {
            'first_name': _('First Name'),
            'last_name': _('Last Name'),
            'email': _('Email'),
            'number': _('Phone Number'),
        }


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ('street', 'street_number', 'country', 'ZIP_code', 'town')
        widgets = {
            'street': forms.TextInput(attrs={'class': 'form-control font_numbers_light input', 'pattern': '^[A-ZŻŹŁ][a-zęóąśłżźćń ]*', 'placeholder': '-----', 'required': 'required', 'disabled': 'true'}),
            'street_number': forms.TextInput(attrs={'class': 'form-control font_numbers_light input', 'pattern': '[0-9][0-9a-zA-Z/-]*', 'placeholder': '-----', 'required': 'required', 'disabled': 'true'}),
            'town': forms.TextInput(attrs={'class': 'form-control font_numbers_light input', 'pattern': '^[A-ZŻŹŁ][a-zęóąśłżźćń ]*', 'placeholder': '-----', 'required': 'required', 'disabled': 'true'}),
            'ZIP_code': forms.TextInput(attrs={'class': 'form-control font_numbers_light input', 'pattern': '[0-9-]*', 'placeholder': '-----', 'required': 'required', 'disabled': 'true'}),
            'country': CountrySelectWidget(attrs={'class': 'form-control font_numbers_light input', 'placeholder': '-----', 'required': 'required', 'disabled': 'true'}),
        }
        labels = {
            'street': _('Street'),
            'street_number': _('Street Number'),
            'country': _('Country'),
            'ZIP_code': _('ZIP Code'),
            'town': _('Town')
        }

sklep_2/apps/shop/views.py
from django.contrib.auth.decorators import login_required
from django.http.response import JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import ListView, DetailView, CreateView
from django.views.generic.base import ContextMixin

from .forms import UserModelForm, PersonalForm, AddressForm
from .models import Address, Category, Product, UserModel
from .recommender import Recommender
from .utils import filter_prices_products, data_post
 

class MainBar(ContextMixin):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['main_bar'] = True
        return context


class Main(ListView, MainBar):
    model = Product
    template_name = 'apps/shop/main.html'
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        return context
    
    def get_queryset(self):
        products = Product.objects.all()
        r = Recommender()
        queryset = r.popular_products(products)
        return queryset
    

class Register(CreateView):
    model = UserModel
    form_class = UserModelForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('shop:login')


class Detail(DetailView, MainBar):
    model = Product
    template_name = 'apps/shop/detail.html'
    context_object_name = 'product'


class List(ListView, MainBar):
    model = Product
    template_name = 'apps/shop/list.html'
    paginate_by = 5
    context_object_name = 'products'
    
    def get_queryset(self):
        if self.kwargs.get('category'):
            category = Category.objects.get(slug=self.kwargs.get('category'))
            queryset = Product.objects.filter(category=category)
        elif self.kwargs.get('search'):
            queryset = Product.objects.filter(name__icontains=self.kwargs.get('search'))
        else:
            queryset = Product.objects.all()
        if self.request.GET.get('filter'):
            queryset = filter_prices_products(self.request.GET, queryset)
        return queryset


@login_required
def account(request, type=None):
    user = UserModel.objects.get(id=request.user.id)
    orders = user.order.values('id', 'created')
       
    if request.method == 'POST':
        address = user.address
        # using own function which is the shop.utils.py throw away the csrftoken from request.POST
        data = data_post(request)

        # assigning data to an object
        if type == 'address':
            for k, v in data.items():  
                if k in address.__dict__:
                    setattr(address, k, v)
            address.save()
        elif type == 'personal_data':
            for k, v in data.items():
                if k in user.__dict__:
                    setattr(user, k, v)
            user.save()
        return redirect('shop:account')
           
    else:
        personal_form = PersonalForm(instance=user)
        address_form = AddressForm(instance=user.address)    
    

    return render(request, 'apps/shop/account.html', {'address_form': address_form,
                                                    'main_bar': True,
                                                    'orders': orders,
                                                    'personal_form': personal_form,
                                                    'user': user}) 


def search(request):
    if request.method == 'POST':
        text = request.POST.get('text')
        products = Product.objects.filter(name__icontains=text)[:8]
        data = []
        if len(products) > 0 and len(text) > 0:     
            for product in products:
                data.append(product.data())
        return JsonResponse({'data': data})

sklep_2/templates/apps/shop/account.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}

{% block content %}
    <div class="basic ">
        <div id='account_background_form'></div>
        <div id='account_div_form'>
            <h3 class='font_numbers_light'>{% trans "Change" %}</h3>
            <div id='account_div_form_address'>
                <form action="{% url 'shop:account_data' type='address' %}" method='post' class='needs-validation' novalidate>
                    {% csrf_token %}
                    <div class="form-floating has-validation  mb-3 display_n" id='street'>
                        {{ address_form.street }}
                        <label for="id_street">{{ address_form.street.label }}</label>
                        <div class="invalid-feedback">
                            <ul>
                                <li>{% trans "The first name must start with a capital letter" %}</li>
                                <li>{% trans "Only letters" %}</li>
                            </ul>
                        </div>
                    </div>
                    <div class="form-floating has-validation mb-3 display_n" id='street_number'>
                        {{ address_form.street_number }}
                        <label for="id_street_number">{{ address_form.street_number.label }}</label>
                        <div class="invalid-feedback">
                            <ul>
                                <li>{% trans "Please enter a valid street number" %}</li>
                            </ul>
                        </div>
                    </div>
                    <div class="form-floating has-validation mb-3 display_n" id='town'>
                        {{ address_form.town }}
                        <label for="id_town">{{ address_form.town.label }}</label>
                        <div class="invalid-feedback">
                            <ul>
                                <li>{% trans "The first name must start with a capital letter" %}</li>
                                <li>{% trans "Only letters" %}</li>
                            </ul>
                        </div>
                    </div>
                    <div class="form-floating has-validation mb-3 display_n" id='ZIP_code'>
                        {{ address_form.ZIP_code }}
                        <label for="id_ZIP_code">{{ address_form.ZIP_code.label }}</label>
                        <div class="invalid-feedback">
                            <ul>
                                <li>{% trans "Only numbers" %}</li>
                            </ul>
                        </div>
                    </div>
                    <div class="form-floating has-validation mb-3 display_n" id='country'>
                        {{ address_form.country }}
                        <label for="id_country">{{ address_form.country.label }}</label>
                        <div class="invalid-feedback">
                            <ul>
                                <li>{% trans "The country must start with a capital letter" %}</li>
                                <li>{% trans "Only letters" %}</li>
                            </ul>
                        </div>
                    </div>
                    <div class='display_f align_i_c float_r margin_t'>
                        <button type='button' class='button_n' onclick='cancel("address")'><p class='color_green margin_0'>{% trans "CANCEL" %}</p></button>
                        <button type='submit' class='button margin_l' ><p class='button_margin'>{% trans "SUBMIT" %}</p></button>
                    </div>
                    
                </form>
            </div>
            <div id='account_div_form_personal_data'>
                <form action="{% url 'shop:account_data' type='personal_data' %}" method='post' class='needs-validation' novalidate>
                    {% csrf_token %}
                    <div class="form-floating has-validation margin_tb display_n" id='first_name'>
                        
                        {{ personal_form.first_name }}
                        <label for="id_first_name">{{ personal_form.first_name.label }}</label>
                        <div class="invalid-feedback">
                            <ul>
                                <li>{% trans "The first name must start with a capital letter" %}</li>
                                <li>{% trans "Only letters" %}</li>
                            </ul>
                        </div>
                    </div>
                    
                    <div class="form-floating has-validation mb-3 display_n" id='last_name'>
                        {{ personal_form.last_name }}
                        <label for="id_last_name">{{ personal_form.last_name.label }}</label>
                        <div class="invalid-feedback">
                            <ul>
                                <li>{% trans "The last name must start with a capital letter" %}</li>
                                <li>{% trans "Only letters" %}</li>
                            </ul>
                        </div>
                    </div>
                    <div class="form-floating has-validation mb-3 display_n" id='email'>
                        {{ personal_form.email }}
                        <label for="id_email">{{ personal_form.email.label }}</label>
                        <div class="invalid-feedback">
                            <ul>
                                <li>{% trans "Please enter a valid email" %}</li>
                            </ul>
                        </div>
                    </div>
                    <div class="form-floating has-validation display_f justify_c_s_b display_n" id='number'>
                        <div class='display_f justify_c_s_b form-floating'>
                            {{ personal_form.number }}
                            <label for="id_phone_number_1">{{ personal_form.number.label }}</label>
                        </div>
                          
                    </div>
                    <div class='display_f align_i_c float_r margin_t'>
                        <button type='button' class='button_n' onclick="cancel('personal_data')"><p class='color_green margin_0'>{% trans "CANCEL" %}</p></button>
                        <button type='submit' class='button margin_l' ><p class='button_margin'>{% trans "SUBMIT" %}</p></button>
                    </div>
                </form>
            </div>
            
        </div> 
        <div id='address_and_bills'>
            <div class='account_address white padding margin_t'>          
                <div class="display_f justify_c_s_b">
                    <h4 class='font_numbers_light display_f align_i_c margin_0'>{% trans "Your address" %}</h1>
                    <button class='color_green button_n font_size_15' onclick="account_form('address', 'all')">{% trans "CHANGE" %}</button>
                </div>                   
                <div class='display_f width_100 flex_w_w'>
      
                    <div class='personal_data width_320p margin_t_2'>
                        <div>
                            <p class='font_numbers font_size_15 color_gray margin_0'>{% trans "Street" %}:</p>   
                            <p class='font_numbers_light margin_0 font_size_12'>{% if user.address.street %}{{ user.address.street }}{% else %}-----{% endif %}</p>
                            <button class='color_green button_n padding_0' onclick="account_form('address', 'street')">{% trans "CHANGE" %}</button>
                        </div>
                    </div>
                    <div class='personal_data width_320p margin_t_2'>
                        <div>
                            <p class='font_numbers font_size_15 color_gray margin_0'>{% trans "Street Number" %}:</p>   
                            <p class='font_numbers_light margin_0 font_size_12'>{% if user.address.street_number %}{{ user.address.street_number }}{% else %}-----{% endif %}</p>
                            <button class='color_green button_n padding_0' onclick="account_form('address','street_number')">{% trans "CHANGE" %}</button>
                        </div>
                    </div>
                    <div class='personal_data width_320p margin_t_2'>
                        <div>
                            <p class='font_numbers font_size_15 color_gray margin_0'>{% trans "Town" %}:</p>   
                            <p class='font_numbers_light margin_0 font_size_12'>{% if user.address.town %}{{ user.address.town }}{% else %}-----{% endif %}</p>
                            <button class='color_green button_n padding_0' onclick="account_form('address','town')">{% trans "CHANGE" %}</button>
                        </div>
                    </div>
                    <div class='personal_data width_320p margin_t_2'>
                        <div>
                            <p class='font_numbers font_size_15 color_gray margin_0'>{% trans "ZIP Code" %}:</p>   
                            <p class='font_numbers_light margin_0 font_size_12'>{% if user.address.ZIP_code %}{{ user.address.ZIP_code }}{% else %}-----{% endif %}</p>
                            <button class='color_green button_n padding_0' onclick="account_form('address','ZIP_code')">{% trans "CHANGE" %}</button>
                        </div>
                    </div>
                    <div class='personal_data width_320p margin_t_2'>
                        <div>
                            <p class='font_numbers font_size_15 color_gray margin_0'>{% trans "Country" %}:</p>   
                            <p class='font_numbers_light margin_0 font_size_12'>{% if user.address.country %}{{ user.address.country.name }}{% else %}-----{% endif %}</p>
                            <button class='color_green button_n padding_0' onclick="account_form('address','country')">{% trans "CHANGE" %}</button>
                        </div>
                    </div>
               
            </div>
            </div>
            <div class='account_bills white padding margin_t'>         
                <h4 class='font_numbers_light'>{% trans "Bills" %}</h1>      
                <div class='overflow_s' id='account_bills_scroll'>
                    {% for order in orders %}
                        <div class='margin_t'><a href={% url 'order:admin_order_pdf' order.id %}><p class='font_numbers_light'>{{ order.created }}</p></a></div>
                    {% endfor %}
                    
                </div>      
            </div>
        </div>
        <div class='white margin_t padding'>
            <div class='width_320p display_f justify_c_s_b align_i_c'>
                <h4 class='font_numbers_light margin_0'>{% trans "Personal data" %}</h1>
                <button class='font_size_15 color_green button_n padding_0' onclick="account_form('personal_data', 'all')">{% trans "CHANGE" %}</button>
            </div>
            
            <div class='display_f width_100 flex_w_w'>
                    <div class='personal_data width_320p'>
                        <div>
                            <p class='font_numbers font_size_12 color_gray margin_0'>{% trans "First Name" %}:</p>   
                            <p class='font_numbers_light margin_0'>{% if user.first_name %}{{ user.first_name }}{% else %}-----{% endif %}</p>
                            <button class='color_green button_n padding_0' onclick="account_form('personal_data', 'first_name')">{% trans "CHANGE" %}</button>
                        </div>
                    </div>
                    <div class='personal_data width_320p'>
                        <div>
                            <p class='font_numbers font_size_12 color_gray margin_0'>{% trans "Last Name" %}:</p>   
                            <p class='font_numbers_light margin_0'>{% if user.last_name %}{{ user.last_name }}{% else %}-----{% endif %}</p>
                            <button class='color_green button_n padding_0' onclick="account_form('personal_data', 'last_name')">{% trans "CHANGE" %}</button>
                        </div>
                    </div>
                    <div class='personal_data width_320p'>
                        <div>
                            <p class='font_numbers font_size_12 color_gray margin_0'>{% trans "Email" %}:</p>   
                            <p class='font_numbers_light margin_0'>{% if user.email %}{{ user.email }}{% else %}-----{% endif %}</p>
                            <button class='color_green button_n padding_0' onclick="account_form('personal_data', 'email')">{% trans "CHANGE" %}</button>
                        </div>
                    </div>
                    <div class='personal_data width_320p'>
                        <div>
                            <p class='font_numbers font_size_12 color_gray margin_0'>{% trans "Phone Number" %}:</p>   
                            <p class='font_numbers_light margin_0'>{% if user.number %}{{ user.number }}{% else %}-----{% endif %}</p>
                            <button class='color_green button_n padding_0' onclick="account_form('personal_data', 'number')">{% trans "CHANGE" %}</button>
                        </div>
                    </div>
            </div>
        </div>
    </div>
    <script type='text/javascript' src='{% static 'assets/js/account.js' %}'></script>
{% endblock content %}