sklep_2/apps/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('added/<str:id>/', views.add_to_cart, name='add'),
    path('remove/<str:id>/', views.RemoveItem.as_view(), name='remove_item'),
    path('', views.MainCart.as_view(), name='main_cart'),
]

sklep_2/apps/coupon/urls.py
from django.urls import path

from . import views


app_name = 'coupon'

urlpatterns = [
    path('coupon/', views.coupon, name='coupon')
]

sklep_2/apps/order/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('', views.order, name='order'),
    path('parcels/', views.ParcelView.as_view(), name='parcel'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

sklep_2/sklep_2/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include


urlpatterns = i18n_patterns(
    # admin
    path('admin/', admin.site.urls),
    # apps
    path('', include('apps.shop.urls', namespace='shop')),
    path('analysis/', include('apps.analysis.urls', namespace='analysis')),
    path('cart/', include('apps.cart.urls', namespace='cart')),
    path('coupon/', include('apps.coupon.urls', namespace='coupon')),
    path('order/', include('apps.order.urls', namespace='order')),
    # authorization
    path('accounts/', include('allauth.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL) 

sklep_2/apps/cart/models.py
from django.db import models

# Create your models here.

sklep_2/apps/cart/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import RedirectView, TemplateView

from .cart import Cart
from apps.coupon.forms import CouponForm
from apps.shop.models import Product
from apps.shop.views import MainBar


class MainCart(TemplateView, MainBar):
    template_name = 'apps/cart/cart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["coupon_form"] = CouponForm()
        return context

        
class RemoveItem(RedirectView):
    url = reverse_lazy('cart:main_cart')

    def get(self, request, *args, **kwargs):
        cart = Cart(request)
        cart.remove(kwargs['id'])
        return super().get(request, *args, **kwargs)


def add_to_cart(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    quantity = int(request.GET.get('quantity'))

    if request.GET.get('cart') == 'cart':
        cart.add(product=product, quantity=quantity, modify_cart=True)
        return redirect('cart:main_cart')
    else:
        cart.add(product=product, quantity=quantity)
        return redirect(product.get_absolute_url())    

sklep_2/templates/apps/cart/cart.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}
{% load price_tags %}

{% block content %}
    <div class='main' id='cart'>
        <div class='width_65'>
            {% for item in cart %}
                <div class='display_f justify_c_c background_w padding_tb margin_tb_05 height_150p' id='cart_item'>
                    <div class='width_150p display_f align_i_c'>
                        <div>
                            <img class='height_100p width_max_150' src="{{ item.image }}" >
                        </div>
                    </div>  
                    <div class='display_f justify_c_s_b width_cart height_80p padding_t_15' >
                        <div class=' width_200p  padding_l '>
                            <p  class='font_size_12 word_b_b_w'>{{ item.name }}</p>
                        </div>
                        <div>
                            <form action="{% url 'cart:add' item.id %}" method='get' class='text_a_c'>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <button type='submit' class="btn  btn-sm border_1sg border_r_0" onclick='minus({{ item.id }})'><i class="fa fa-minus"></i></button>
                                    </div>
                                    <input   class="input{{ item.id }} form-control-sm border_1sg width_4 border_1sg border_r_0 text_a_c font_numbers" value="{{ item.quantity }}" min="1" name='quantity'>
                                    <div class="input-group-prepend">
                                        <button type='submit' class="btn  btn-sm border_1sg border_r_0"  onclick='plus({{ item.id }})'><i class="fa fa-plus"></i></button>
                                    </div>
                                </div>
                                <input type="hidden" value='cart' name='cart'>
                            </form>
                        </div>
                        <div>
                            <div class='width_100 text_a_c display_ib'>
                                <span class='font_size_2 font_numbers'>{{ item.total_price|price_front }}</span><span class='font_size_15 font_numbers' >{{ item.total_price|price_back }}</span>
                            </div>
                            <div class='width_200p text_a_c'>
                                <span class='font_size_12 font_numbers_light'>{% trans "for each" %} {{ item.price }}</span>
                            </div>
                        </div>
                        <div>
                            <a href="{% url 'cart:remove_item' item.id %}">
                                <div class='display_f align_i_c'>
                                    <i class="far fa-trash-alt font_size_2"></i>
                                </div>
                            </a>
                        </div>
                        
                    </div>
                </div> 


                <div id='cart_media'>
                    <div class='width_150p height_100 flex_d_c justify_c_s_a'>
                        <div class='text_a_c'>
                            <img class='height_80p width_max_150' src="{{ item.image }}" >
                        </div>
                        <div>
                            <form action="{% url 'cart:add' item.id %}" method='get' class='text_a_c'>
                                <div class="input-group mb-3 button_quantity_cart">
                                    <div class="input-group-prepend">
                                        <button type='submit' class="btn  btn-sm border_1sg border_r_0" onclick='minus({{ item.id }})'><i class="fa fa-minus"></i></button>
                                    </div>
                                    <input  class="input{{ item.id }} form-control-sm border_1sg width_4 border_1sg border_r_0 text_a_c font_numbers" value="{{ item.quantity }}" min="1" name='quantity'>
                                    <div class="input-group-prepend">
                                        <button type='submit' class="btn  btn-sm border_1sg border_r_0" onclick='plus({{ item.id }})' ><i class="fa fa-plus"></i></button>
                                    </div>
                                </div>
                                <input type="hidden" value='cart' name='cart'>
                            </form>
                        </div>
                    </div> 
                    <div class='display_f flex_d_c justify_c_s_b height_100 width_cart'>
                        <div class='width_100 padding_l'>
                            <p  class='font_size_12 word_b_b_w'>{{ item.name }}</p>
                        </div>
                        <div class='flex_d_c'>
                            <div class='text_a_c display_ib float_r'>
                                <span class='font_size_2 font_numbers'>{{ item.total_price|price_front }}</span><span class='font_size_15 font_numbers' >{{ item.total_price|price_back }}</span>
                            </div>
                            <div id='for_each' class='text_a_c '>
                               <p class='font_numbers_light'>{% trans "for each" %}  {{ item.price }}</p>
                            </div>   
                        </div>
                    </div>                   
                </div>                
            {% endfor %}
            <div class='white padding_tb '>
                <div class='width_90 margin_0auto'>
                    <h4>{% trans "Discount" %}</h4>
                    <hr>
                    <form action='{% url 'coupon:coupon' %}' method='post' class='display_f'>
                        {% csrf_token %}
                        {{ coupon_form.code }}
                        <button type='submit' class='button margin_l' id='coupon_button'><p class='button_margin'>{% trans "add" %}</p></button>
                    </form>
                </div>
            </div>
        </div>
        <div class="width_30 background_w margin_tb_05 min_h_300p">
            <div class='flex_d_c align_i_c top_25 position_r'>
                {% if cart.check_coupon %}
                    <div class='width_90'>
                        <div class='display_ib float_r cart_size_total_value'>
                            <span class='font_size_2 font_numbers color_gray'><del>{{ cart.total_value_cart|price_front }}</del></span><span class=' color_gray font_size_15 font_numbers'><del>{{ cart.total_value_cart|price_back }}</del></span>
                        </div>
                    </div>

                    <div class='width_90 padding_b_2'>
                        <div class='display_ib float_r cart_size_total_value'>
                            <span class='font_size_12 padding_r_05'>{% trans "TO PAY" %}</span>
                            <span class='font_size_2 font_numbers'>{{ cart.total_value_cart_after_discount|price_front }}</span><span class='font_size_15 font_numbers'>{{ cart.total_value_cart_after_discount|price_back }}</span>
                        </div>
                    </div>
                {% else %}
                    <div class='width_90 padding_b_2'>
                        <div class='display_ib float_r cart_size_total_value'>
                            <span class='font_size_12 padding_r_05'>{% trans "TO PAY" %}</span>
                            <span class='font_size_2 font_numbers'>{{ cart.total_value_cart|price_front }}</span><span class='font_size_15 font_numbers'>{{ cart.total_value_cart|price_back }}</span>
                        </div>
                    </div>
                {% endif %}
                <button type='submit' class='button width_90 margin_b'><a href="{% url 'order:order' %}"><p class='button_margin'>{% trans "PAYMENT" %}</p></a></button>
                <button class='button width_90 margin_b' ><p class='button_margin '>{% trans "CONTINUE" %}</p></button>
            </div>
        </div>
    </div>
    <script type='text/javascript' src='{% static 'assets/js/cart.js' %}'></script>
{% endblock content %}