sklep_2/apps/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('added/<str:id>/', views.add_to_cart, name='add'),
    path('remove/<str:id>/', views.RemoveItem.as_view(), name='remove_item'),
    path('', views.MainCart.as_view(), name='main_cart'),
]

sklep_2/apps/shop/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

app_name = 'shop'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('shop:password_change_done')), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('shop:password_reset_done')), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('shop:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('register/', views.Register.as_view(), name='register'),
    path('account/', views.account, name='account'),
    path('account/<str:type>/', views.account, name='account_data'),
    path('detail/<str:slug>/<int:seconds>/<int:hours>/<int:id>/', views.Detail.as_view(), name='detail'),
    path('list/category/<str:category>/', views.List.as_view(), name='list_category'),
    path('list/search/<str:search>/', views.List.as_view(), name='list_search'),
    path('list/', views.List.as_view(), name='list'),
    path('search/', views.search, name='search'),
    path('', views.Main.as_view(), name='main'),
]

sklep_2/sklep_2/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include


urlpatterns = i18n_patterns(
    # admin
    path('admin/', admin.site.urls),
    # apps
    path('', include('apps.shop.urls', namespace='shop')),
    path('analysis/', include('apps.analysis.urls', namespace='analysis')),
    path('cart/', include('apps.cart.urls', namespace='cart')),
    path('coupon/', include('apps.coupon.urls', namespace='coupon')),
    path('order/', include('apps.order.urls', namespace='order')),
    # authorization
    path('accounts/', include('allauth.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL) 

sklep_2/templates/base.html
{% load i18n %}
{% load static %}

{% load price_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static '/assets/css/base.css' %}"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>Sklep_2</title>
</head>
<body>
    {% if main_bar %}
        <div id="main">
            <header class='main_flex'>
                <div id='dlogo'>
                    <a href="{% url 'shop:main' %}"><h1 class="logo">SKLEP_2</h1></a>
                </div>
                
                <div id='search' class="width_max_400 margin_0auto">              
                    <form action="{% url 'shop:list' %}" method='GET' class="d-flex" id='search_form_list'>
                        <input id="input_search" class="form-control me-2 input" type="search" placeholder={% trans "Search" %} >
                        
                        <button type='submit' class='button'><p class='button_margin'>{% trans "SEARCH" %}</p></button>
                        
                    </form>
                </div>
                <div id='main_icon' >
                    <div id='main_icons'>
                        {% if cart.cart  %}
                            <a href="{% url 'cart:main_cart' %}">
                                <div class='float_l left_icon' id='cart_icon'>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-bag" viewBox="0 0 16 16">
                                        <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V5z"/>
                                    </svg>
                                </div>
                            </a>
                        {% else %}
                            <div class='float_l left_icon' id='cart_icon'>
                                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-bag" viewBox="0 0 16 16">
                                    <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V5z"/>
                                </svg>
                            </div>
                        {% endif %}
                        
                        <div class='float_r wrapper' onclick="sidebar()">
                            <div id="toggle_grid">
                                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-caret-up "  viewBox="0 0 16 16">
                                    <path d="M3.204 11h9.592L8 5.519 3.204 11zm-.753-.659 4.796-5.48a1 1 0 0 1 1.506 0l4.796 5.48c.566.647.106 1.659-.753 1.659H3.204a1 1 0 0 1-.753-1.659z"/>
                                </svg>
                            </div>
                            
                        </div>
                    </div>
                </div>
                
            </header>

            <div class='main position_r'>
                <div id='shopping_cart_bar' class='background_g'>
                    {% if cart.cart %}
                            <div class='display_f justify_c_s_b  background_w margin_tb_05'>
                                <div class='padding_lr'>
                                    <strong><p class='font_size_15'>{% trans "Cart" %}</p></strong>
                                </div>
                                <div class='display_f align_i_c'>
                                    <div class='padding_lr  display_ib '>
                                        <span class=' font_size_12 padding_r_05'>{% trans "cart value" %}:</span><span class='font_size_2 font_numbers'>{{ cart.total_value_cart|price_front }}</span><span class='font_size_15 font_numbers' >{{ cart.total_value_cart|price_back }}</span>
                                    </div>
                                </div>                                    
                            </div>
                        {% for item in cart %}
                            <div class='display_f justify_c_s_a padding_tb background_w margin_tb_05'>
                                <div class='width_200p   text_a_c'>
                                    <img src="{{ item.image }}" class='height_100p  width_max_150'>
                                </div>
                                <div class='width_200p text_a_c word_b_b_w display_f align_i_c  padding_l_05'>
                                    <p>{{item.quantity}} x {{ item.name }}</p>
                                </div>
                                <div class='display_f align_i_c'>
                                    <div class='width_100p text_a_c display_ib'>
                                        <span class='font_size_2 font_numbers'>{{ item.price|price_front }}</span><span class='font_size_15 font_numbers' >{{ item.price|price_back }}</span>
                                    </div>
                                </div>
                            </div>  
                        {% endfor %}
                    {% else %}
                        <img src="{% static 'img/empty_cart.png' %}" class='width_100 height_100'>
                    {% endif %}

                </div>
                <div class='toggle_bar'>
                    <div class='width_100 '>
                        <div class='display_f padding_b'>
                            <div class='toggle_mode' id='mode_account'>
                                <a href="{% url 'shop:account' %}"><p class='color_green margin_0 padding_tb_05'>{% trans "ACCOUNT" %}</p></a>
                            </div>
                            <div class='toggle_mode' id='mode_analysis'>
                                <a href="{% url 'analysis:main' %}"><p class='margin_0 color_green padding_tb_05'>{% trans "ANALYSIS" %}</p></a>
                            </div>
                            <div class='toggle_mode' id='mode_main'>
                                <a href="{% url 'shop:main' %}"><p class='margin_0 color_green padding_tb_05'>{% trans "MAIN" %}</p></a>
                            </div>
                        </div>
                        <div>
                            {% get_current_language as LANGUAGE_CODE %}
                            {% get_available_languages as LANGUAGES %}
                            {% get_language_info_list for LANGUAGES as languages %}
                            <select  class="btn  width_100 " onchange="location = this.value">
                                <option class="btn">{% trans "Language" %}</option>
                                {% for language in languages %}
                                    <option  value="/{{ language.code }}/" {% if language.code == LANGUAGE_CODE %} class="selected"{% endif %}>
                                            {{ language.name_local }}
                                    </option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="toggle_bar_button">
                        {% if user.is_authenticated %}
                            <a href="{% url 'shop:logout' %}?next={{ request.path }}"><button class="button width_100 color_white">{% trans "LOGOUT" %}</button></a>
                        {% else %}
                            <a href="{% url 'shop:login' %}?next={{ request.path }}"><button class="button width_100 color_white">{% trans "LOGIN" %}</button></a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class='main' id='main_filling'>
        </div>
        <div class="search_box">
            <div class="list-group" id="list_search_box" >       
                {% comment %} <a href="#" class="list-group-item list-group-item-action " aria-current="true">{{ product.name}}</a>   {% endcomment %}
            </div>
        </div>
    {% else %}
        <div id="main_registration">
            <header class='main_flex'>
                <div>
                    <a href="{% url 'shop:main' %}"><h1 class="logo">SKLEP_2</h1></a>
                </div>
            </header>    
        </div>
    {% endif %}

    {% block content %}    
    {% endblock content %}

    <script type="text/javascript" src="{% static 'assets/js/base.js' %}"></script>
</body>
</html>